// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using backend.Data;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20260418175512_reminder-structure")]
    partial class reminderstructure
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("backend.Models.Medication", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SideEffects")
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Medications");
                });

            modelBuilder.Entity("backend.Models.MedicationReminder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ReminderPlanningId")
                        .HasColumnType("integer");

                    b.Property<int>("medicationScheduleId")
                        .HasColumnType("integer");

                    b.Property<TimeOnly>("reminderHour")
                        .HasColumnType("time without time zone");

                    b.HasKey("Id");

                    b.HasIndex("ReminderPlanningId");

                    b.HasIndex("medicationScheduleId");

                    b.ToTable("MedicationReminders");
                });

            modelBuilder.Entity("backend.Models.MedicationSchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("duration")
                        .HasColumnType("integer");

                    b.Property<int>("medicationId")
                        .HasColumnType("integer");

                    b.Property<int>("numberOfPills")
                        .HasColumnType("integer");

                    b.Property<int>("userId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("medicationId");

                    b.HasIndex("userId");

                    b.ToTable("MedicationSchedules");
                });

            modelBuilder.Entity("backend.Models.ReminderPlanning", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("medicationScheduleId")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("reminderDay")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("medicationScheduleId");

                    b.ToTable("ReminderPlannings");
                });

            modelBuilder.Entity("backend.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("backend.Models.MedicationReminder", b =>
                {
                    b.HasOne("backend.Models.ReminderPlanning", null)
                        .WithMany("medicationReminders")
                        .HasForeignKey("ReminderPlanningId");

                    b.HasOne("backend.Models.MedicationSchedule", "medicationSchedule")
                        .WithMany()
                        .HasForeignKey("medicationScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("medicationSchedule");
                });

            modelBuilder.Entity("backend.Models.MedicationSchedule", b =>
                {
                    b.HasOne("backend.Models.Medication", "medication")
                        .WithMany()
                        .HasForeignKey("medicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.User", "user")
                        .WithMany()
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("medication");

                    b.Navigation("user");
                });

            modelBuilder.Entity("backend.Models.ReminderPlanning", b =>
                {
                    b.HasOne("backend.Models.MedicationSchedule", "medicationSchedule")
                        .WithMany("reminderPlannings")
                        .HasForeignKey("medicationScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("medicationSchedule");
                });

            modelBuilder.Entity("backend.Models.MedicationSchedule", b =>
                {
                    b.Navigation("reminderPlannings");
                });

            modelBuilder.Entity("backend.Models.ReminderPlanning", b =>
                {
                    b.Navigation("medicationReminders");
                });
#pragma warning restore 612, 618
        }
    }
}
